# R code {#r-code}

Everyone has their own coding style and formats.
There are however some best practice guidelines that [_Bioconductor_](https://bioconductor.org/) reviewers will look for (see [coding style](http://bioconductor.org/developers/how-to/coding-style/)).

There are also some other key points, detailed in the following sections.

## License

Only contain code that can be distributed under the license specified (see also [The DESCRIPTION file](the-description-file.html#license)).

## `R CMD check` and `BiocCheck`

Many common coding and sytax issues are flagged in `R CMD check` and `BiocCheck()` (see the `R CMD check` [cheatsheet](http://r-pkgs.had.co.nz/check.html) and `r BiocStyle::Biocpkg("BiocCheck", vignette = "BiocCheck.html")` vignette.

Some of the more prominent offenders:

* Use `vapply()` instead of `sapply()`, and use the various `apply` functions instead of `for` loops.
* Use `seq_len()` or `seq_along()` instead of `1:...`.
* Use `TRUE` and `FALSE` instead of `T` and `F`.
* Use of numeric indices (rather than robust named indices).
* Use `is()` instead of `class() ==` and `class() !=`.
* Use `system2()` instead of `system()`.
* Do not use `set.seed()` in any internal <i class="fab fa-r-project"></i> code.
* Do not use `browser()` in any internal <i class="fab fa-r-project"></i> code.
* Avoid the use of `<<-`.
* Avoid use of direct slot access with `@` or `slot()`.
  Accessor methods should be created and utilized
* Use the packages `r BiocStyle::Biocpkg("ExperimentHub")` and `r BiocStyle::Biocpkg("AnnotationHub")` instead of downloading external data from unsanctioned providers such as <i class="fab fa-github"></i> GitHub, <i class="fa fa-dropbox" aria-hidden="true"></i> Dropbox, etc.
* Use `<-` instead of `=` for assigning variables outside function calls.

### Formatting and syntax

* Use `<-` instead of = for assignment.
* Function names should be `camelCase` or utilize the underscore `_` and not have a dot `.` (which indicates S3 dispatch).
* Use `dev.new()` to start a graphics drive if necessary.
  Avoid using `x11()` or `X11()`, for it can only be called on machines that have access to an X server.
* Use the functions `message()`, `warning()` and `error()`, instead of the `cat()` function (except for customized `show()` methods).
  `paste0()` should generally not be used in these methods except for collapsing multiple values from a variable.

### Re-use functionality and classes 

Avoid re-implementing functionality or classes (see also [The DESCRIPTION file](the-description-file.html#depends-imports-suggests-enhances)).
Make use of appropriate existing packages (e.g., `r BiocStyle::Biocpkg("biomaRt")`, `r BiocStyle::Biocpkg("AnnotationDbi")`, `r BiocStyle::Biocpkg("Biostrings")`, `r BiocStyle::Biocpkg("GenomicRanges")`) and classes (e.g., `r BiocStyle::Biocpkg("SummarizedExperiment")`, `r BiocStyle::Biocpkg("AnnotatedDataFrame")`, `r BiocStyle::Biocpkg("GRanges")`, `r BiocStyle::Biocpkg("DNAStringSet")`) to avoid duplication of functionality available in other [_Bioconductor_](https://bioconductor.org/) packages.
See also [Common Bioconductor Methods and Classes](https://bioconductor.org/developers/how-to/commonMethodsAndClasses/).

This encourages interoperability and simplifies your own package development.
If a new representation is needed, see the [Essential S4 interface](https://bioconductor.org/developers/how-to/efficient-code/#essential-s4-interface) section of [Robust and Efficient Code](https://bioconductor.org/developers/how-to/efficient-code).
In general, [_Bioconductor_](https://bioconductor.org/) will insist on interoperability with [Common Classes](https://bioconductor.org/developers/how-to/commonMethodsAndClasses/) for acceptance.

### Functional programming

Avoid large chunks of repeated code.
If code is being repeated this is generally a good indication a helper function could be implemented.

### Function length

Excessively long functions should also be avoided.
Write small functions.

It is best if each function has only one job that it needs to do.
And it is also best if that function does that job in as few lines of code as possible.
If you find yourself writing great long functions that extend for more than a screen, then you should probably take a moment to split it up into smaller helper functions.

Smaller functions are easier to read, debug and to reuse.

### Function arguments

Argument names to functions should be descriptive and well documented.
Arguments should generally have default values.
Check arguments against a validity check.

### Vectorization

Vectorize!

Many R operations are performed on the whole object, not just the elements of the object (e.g., `sum(x)` instead of `x[1] + x[2] + x[2] + ...`).
In particular, relatively few situations require an explicit `for` loop.
See the [Vectorize](https://bioconductor.org/developers/how-to/efficient-code/#vectorize) section of [Robust and Efficient Code for additional detail](https://bioconductor.org/developers/how-to/efficient-code).

### Web resources

Follow guiding principles on [Querying Web Resources](http://bioconductor.org/developers/how-to/web-query/), if applicable.

### Parallelisation

For parallel implementation please use `r BiocStyle::Biocpkg("BiocParallel")`.
See also the [Parallel Recommendations](https://bioconductor.org/developers/how-to/efficient-code/#parallel-recommendations) section of [Robust and Efficient Code](https://bioconductor.org/developers/how-to/efficient-code).

A minimal number of cores (1 or 2) should be set as a default.

### File caching

Files downloaded should be cached.
Please use `r BiocStyle::Biocpkg("BiocFileCache")`.

### Additional files and dependencies

Do NOT install anything on a users system.

System dependencies, applications, and additionally needed packages should be assumed already present on the user's system.

If necessary, package maintainers should provide instructions for download and setup, but should not execute those instructions on behalf of a user.
