# Shiny apps {#shiny}

[Shiny apps][shiny-rstudio] can be submitted to _Bioconductor_ as software packages.

## Code organisation

Shiny apps are divided into two parts:

- User interface (UI)
- Server

Shiny apps submitted to _Bioconductor_ must store the <i class="fab fa-r-project"></i> code for both the UI and server code under the `R/` directory of the package.

The bulk of the package code should **not** be implemented directly within the `shinyApp()` function call.
Instead, components

## Building the package

_Coming soon: comments on build issues for packages that contain Shiny apps._

## Testing

The use of `# nocov start` and `# nocov end` is allowed to ignore part of the code that cannot be tested using traditional unit tests (e.g., observers).

For instance:

```{r, eval=FALSE}
# nocov start
observeEvent(input[[.ui_dataset_columns]], {
    pObjects[[.ui_dataset_columns]] <- input[[.ui_dataset_columns]]
    rObjects$rerender_datasets <- iSEE:::.increment_counter(isolate(rObjects$rerender_datasets))
})
# nocov end
```

Use files `setup-*.R` in the subdirectory `tests/testthat/` to generate only once objects that are used repeatedly as input for the unit tests.

## Review

_Coming soon: comments on reviewing packages that contain Shiny apps (e.g., points raised during the review process)._
